background {
    monitor =
    path = /home/rguidry/Pictures/Wallpapers/arch.png
    blur_passes = 2
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    outer_color = rgb(7ec8e3)
    inner_color = rgb(0a1a2a)
    font_color = rgb(cce8ff)
    placeholder_text = <i>Password...</i>
}
